Update#843 - adds discord info to userInfo GraphQL query
garageScript/c0d3-app pull request #1101
Opened 2021-08-31 15:53 UTC by kondanna

- adds discordUsername and discordAvatarUrl to userInfo query
- next step: have pages/profile/[username] to display this info

currently tests are wrong so I gotta fix them

2021-09-01 17:24 UTC, songz approved these changes

2021-09-01 19:15 UTC, tomrule007 requested changes
Just the one change allowing us to remove lodash from the controller

2021-09-01 19:15 UTC, tomrule007 commented on helpers/controllers/userInfoController.ts
> +      discordAvatarUrl = _.get(discordUserInfo, 'avatarUrl', '')
can we get rid of lodash here and just use the newer js syntax  ` discordUsername = discordUserInfo?. username ??  ''`

2021-09-02 14:58 UTC, tomrule007 approved these changes

2021-09-02 17:31 UTC, merged