Mitigate the issue of creating a submission based on the cliToken ID
garageScript/c0d3-app pull request #1553
Opened 2022-03-07 20:55 UTC by flacial

Closes #1551 

This PR will:
- Populate the user object based on the cliToken if it's available
- Retrieve the user ID from the req.user object rather than the `cliToken`

2022-03-07 21:00 UTC, songz approved these changes

2022-03-08 19:14 UTC, SahilKalra98 approved these changes

2022-03-08 21:23 UTC, songz requested changes

2022-03-08 21:23 UTC, songz commented on helpers/controllers/submissionController.ts
> +  const id = !req.user || !req.user.id ? decodedCliToken.id : req.user.id
same security bug. `decodedCliToken.id` should be 

```js
const user = await prisma.user.findFirst({
      where: { cliToken: decodedCliToken.cliToken }
    })
    
 id = user.id
```

2022-03-08 23:24 UTC, songz commented on helpers/controllers/submissionController.ts
> +  let id = !req.user ? decodedCliToken.id : req.user.id
bad coding practice to have double negatives: `!req.user` unless you absolutely have to, which is not the case here.

```js
let id = _.get(req, 'user.id')
if (!id && cliToken) {
  const user = ...
  id = user!?.id
}
```

2022-03-08 23:25 UTC, songz commented on helpers/controllers/submissionController.ts
> +  const decodedCliToken: CliToken = cliToken && decode(cliToken)
move this inside the `if (!id && cliToken)` check below, its not needed until then.

2022-03-09 16:43 UTC, songz approved these changes

2022-03-09 20:24 UTC, merged