Update Error page
garageScript/c0d3-app pull request #1686
Opened 2022-04-03 19:22 UTC by rsrelewa

This PR updated the error pages with new symbols, error messages and overall made things look pleasing to look at. 
![Screenshot_2022-04-03_15-21-01](https://user-images.githubusercontent.com/81452711/161444457-5608b52d-6d74-4085-9719-88545d594fa4.png)

2022-04-03 19:29 UTC, flacial commented on components/theme/sizes.tsx
> -  xl: '1.5rem'
I think it would've been better to create another one called `xxl: 3rem` for example.

2022-04-03 19:31 UTC, flacial commented
Each component that could be reused must have a [story](https://storybook.js.org/docs/react/get-started/whats-a-story). The error component already has a [story](https://deploy-preview-1637--youthful-thompson-448332.netlify.app/?path=/story/components-error--not-found), you could modify it instead of creating a new one.

2022-04-04 15:10 UTC, mino323 approved these changes

2022-04-05 02:35 UTC, anthonykhoa commented on components/admin/AdminLayout.tsx
> +        code={403}
Please use the `StatusCode` enum here instead of hardcoding the value for the `code` prop

2022-04-05 20:09 UTC, SahilKalra98 approved these changes

2022-04-13 16:10 UTC, flacial commented
The margin between the elements is small, what about giving the image a margin-bottom of `50px` and the `404 Error` a padding-bottom of `27.2px`

And... for the aesthetics: a drop-shadow `filter: drop-shadow(0px 5px 20px hsl(247.9deg, 66.1%, 80.9%));`

![image](https://user-images.githubusercontent.com/35906419/163223839-87132602-fa68-4c82-bc92-075a084954ad.png)

2022-04-13 16:12 UTC, flacial commented
It's hard to read horizontally long text. Perhaps it can be given a max-width of `500px`.

![image](https://user-images.githubusercontent.com/35906419/163224121-56786af6-3964-4b80-b7cc-554e545d7f80.png)

2022-04-17 19:15 UTC, flacial approved these changes

2022-04-18 03:28 UTC, flacial requested changes
It's mostly about CSS.

Also, I hope you get well and healthy!

2022-05-01 19:19 UTC, songz commented
Closing due to inactivity

2022-05-01 19:19 UTC, closed without merging