fix: PT-MONO font doesn't load
garageScript/c0d3-app pull request #1783
Opened 2022-04-26 05:14 UTC by flacial

Closes #1781 

This PR replaces the font name from `PT MONO` to `PT-MONO`.

2022-04-26 15:31 UTC, songz approved these changes

2022-04-26 15:58 UTC, SlyBouhafs approved these changes

2022-04-26 16:08 UTC, SlyBouhafs reviewed
I checked the preview on another device and the fix doesn't seem to be working.

2022-04-26 16:58 UTC, SlyBouhafs requested changes
I don't think the font name matters at all, when i used google to load the font, the font worked straight away without having to change the name.
`@import url('https://fonts.googleapis.com/css2?family=PT+Mono&display=swap');`
you can try it here: http://164.92.183.234:3002/

Edit: After reading this: https://nextjs.org/docs/basic-features/static-file-serving
It seems that there is no need to add `/public` to the path when using Nextjs.

2022-04-26 19:34 UTC, flacial commented
>  It seems that there is no need to add /public to the path when using Nextjs.

I think this is exclusive for components and pages, but for SCSS files we need to explicitly add `/public`.

2022-04-27 14:35 UTC, SlyBouhafs approved these changes

2022-04-27 18:02 UTC, songz approved these changes

2022-04-27 18:20 UTC, merged